-- Boxes
-- 1 = Family Friendly
-- 2 = Pet Lovers
-- 3 = Active Lifestyle
-- 4 = Health & Wellness
-- 5 = Food & Drink

-- Family Friendly (1)
{ name: "My Geek Box", bucket_id: 1, price: 9.99, image_url: "https://urbantastebuds-wpengine.netdna-ssl.com/wp-content/uploads/2016/12/box-image-013329.jpg", description: "When you join My Geek Box, you’ll receive 5 to 7 handpicked geek surprises delivered monthly."}
{ name: "Squix", bucket_id: 1, price: 4.95, image_url: "https://urbantastebuds-wpengine.netdna-ssl.com/wp-content/uploads/2017/01/SQ_QBox_Landing_Page_Reposition_v2-1024x748.jpg", description: "When you join Squix, you’ll receive a box of some of Squix’s favorite and most innovative cleaning products. Inside ever box, you’ll get 3 full sized cleaning products as wells as some great free gifts. And don’t worry, you’ll be able to customize what products you want each month."}
{ name: "Vellabox", bucket_id: 1, price: 10.00, image_url: "https://urbantastebuds-wpengine.netdna-ssl.com/wp-content/uploads/2017/01/e5a7bdc3204d11768f6954b99e0587b7.jpg", description: "When you sign up for Vellabox’s Lucerna plan, you’ll get one 4 oz candle per month as well as a surprise gift. And each candle can burn for alt least 25 hours. This is easily one of the best candle subscription boxes out there today!"}
{ name: "CAUSEBOX", bucket_id: 1, price: 54.95, image_url: "https://s3.amazonaws.com/msa-production/boxes/images/000/000/683/medium/Screen_Shot_2018-02-06_at_2.08.48_PM.png?1517944426", description: "CAUSEBOX is a seasonal delivery of 5-8 hand-curated products, including jewelry, fashion, home decor, beauty products, artwork, and more, all from socially conscious companies. Every product has a story and makes the world better."}
{ name: "Accio!", bucket_id: 1, price: 39.99, image_url: "https://img.buzzfeed.com/buzzfeed-static/static/2017-12/19/13/asset/buzzfeed-prod-fastlane-02/sub-buzz-27160-1513709734-1.jpg?downsize=1300:*&output-format=auto&output-quality=auto", description: "Choose your house and open your door each month to four to five Potter-themed products such as candles, bath and body items, decor, and special collectibles."}
{ name: "Nostalgia Crate", bucket_id: 1, price: 10.00, image_url: "https://img.buzzfeed.com/buzzfeed-static/static/2017-12/19/14/asset/buzzfeed-prod-fastlane-02/sub-buzz-27317-1513710305-2.jpg?downsize=1500:*&output-format=auto&output-quality=auto", description: "Out-of-print toys from the '80s, '90s, and '00s, including comics, trading cards, and video games. Something different in every box!"}
{ name: "My First Reading Club", bucket_id: 1, price: 9.99, image_url: "https://img.buzzfeed.com/buzzfeed-static/static/2017-12/19/13/asset/buzzfeed-prod-fastlane-01/sub-buzz-6821-1513709446-1.jpg?downsize=1500:*&output-format=auto&output-quality=auto", description: "Each month you'll get a package of three board books and one activity book for the kiddo(s) – there's six subscription options ranging in ages birth to 12. Plus, there's a fun little surprise for mom!"}
{ name: "Themepark Monthly", bucket_id: 1, price: 8.95, image_url: "https://img.buzzfeed.com/buzzfeed-static/static/2017-12/19/14/asset/buzzfeed-prod-fastlane-03/sub-buzz-32620-1513710426-1.jpg?crop=600:362;0,16&downsize=1500:*&output-format=auto&output-quality=auto", description: "Hand-picked goodies from Walt Disney World and The Wizarding World of Harry Potter. What more could you ask for?"}
{ name: "The Preschool Box", bucket_id: 1, price: 29.95, image_url: "https://img.buzzfeed.com/buzzfeed-static/static/2017-12/19/13/asset/buzzfeed-prod-fastlane-02/sub-buzz-26300-1513708690-6.jpg?downsize=1500:*&output-format=auto&output-quality=auto", description: "A fun box filled with simple, educational activities for the little ones that focus on topics like phonics, counting, shapes, colors, and writing through hands-on activities and games. Who said learning couldn't be tons of fun? Not these guys!"}
{ name: "Monti Kids", bucket_id: 1, price: 297.00, image_url: "https://thumbor.forbes.com/thumbor/960x0/smart/https%3A%2F%2Fblogs-images.forbes.com%2Fsboyd%2Ffiles%2F2017%2F11%2Fmonti-kids.jpg", description: "Kids need subscription services too! Based on the Montessori method, Monti Kids delivers wooden toys that are safe for children under 3 to use and stimulate their developmental growth. Every three months, Monti Kids will send out a new level of toys as the child learns and grows. An added feature that I love: once a child outgrows their old Monti Kids toys, you have the option of donating them to underserved children."}

-- Pet Lovers (2)
{ name: "The Dapper Dog Box", bucket_id: 2, price: 29.99, image_url: "https://img.buzzfeed.com/buzzfeed-static/static/2017-12/19/13/asset/buzzfeed-prod-fastlane-03/sub-buzz-31768-1513709235-2.jpg?downsize=1500:*&output-format=auto&output-quality=auto", description: "Each month you'll open a box of five to eight items for your beloved pupper like toys, natural treats, clothing items, and more. All that's required on your end is a brief survey about your dog, so the box is filled with quality items tailored just to them!"}
{ name: "KitNipBox", bucket_id: 2, price: 19.99, image_url: "https://img.buzzfeed.com/buzzfeed-static/static/2017-12/10/10/asset/buzzfeed-prod-fastlane-03/sub-buzz-28879-1512919204-2.jpg?downsize=1500:*&output-format=auto&output-quality=auto", description: "A box filled with an assortment of goods to keep your furry friend happy like toys, treats, accessories, hygiene products, gadgets, and more! Note that treats and food items only come in U.S. boxes, and you may opt out of receiving food if your kitty has a sensitive tummy."}
{ name: "Bullymake Box", bucket_id: 2, price: 39.99, image_url: "https://bullymake.com/wp-content/uploads/2016/07/13531818_1710090005932498_1251761523_n-1-1036x1024.jpg", description: "Bullymake has one goal: To bring a subscription box that’s suitable for power chewing pups!"}
{ name: "BarkBox", bucket_id: 2, price: 29.99, image_url: "https://asset1.mysubscriptionaddiction.com/wp-content/uploads/2017/01/Barkbox-January-2017-0003-1024x1024.jpg", description: "BarkBox is a monthly subscription box for dogs that sends you toys, treats, and grooming products perfect for your dog based on their size. We’re so glad our readers love it, because it’s one of our favorite subscription boxes too – our dog loves it, and we’ve gifted it to dogs in our extended family as well!"}
{ name: "Purr Pack", bucket_id: 2, price: 16.99, image_url: "https://asset1.mysubscriptionaddiction.com/wp-content/uploads/2017/02/purr-packs-february-2017-review-963x1024.jpg", description: "Purr Packs is a monthly subscription box for cats. You can choose from several different subscription tiers, with customization offered for higher tiers (for example, you can exclude certain protein sources in treats). Pricing ranges from $16.99/month to $39.99/month."}
{ name: "Loot Pet", bucket_id: 2, price: 19.99, image_url: "https://urbantastebuds-wpengine.netdna-ssl.com/wp-content/uploads/2016/11/pets-open-graph-eee0280d721793d0a4d02f1b5dd84b4eca816fcddde284ff06817395a4f828ec-1024x538.jpg", description: "With LootPets, you’ll get fun dog toys and delicious treats (valued over $50) delivered to your door every month. But there’s a twist – each item in your box is themed based off of popular movies like Lord of the Rings, Star Wars, Marvel movies, and other fun and geeky things! And don’t worry, there’s a Loot Crate for geeky humans too."}
{ name: "VetPet Box", bucket_id: 2, price: 35.00, image_url: "https://urbantastebuds-wpengine.netdna-ssl.com/wp-content/uploads/2016/11/vet-pet-whats-inside-1.jpg", description: "Each month, you’ll receive a monthly pet box filled with nutritious treats, premium toys, accessories, and exam room recommended well products carefully selected by their team of veterinarians. Best of all, there’s a box for both cats and dogs!"}
{ name: "Saddle Box", bucket_id: 2, price: 34.95, image_url: "https://urbantastebuds-wpengine.netdna-ssl.com/wp-content/uploads/2016/11/23331019_700654423461373_6897328013486382738_o.jpg", description: "The perfect box for horse owners! Every month, you’ll get full-sized gourmet horse treats, grooming tools and products, tack, and more."}
{ name: "Rescue Box", bucket_id: 2, price: 29.95, image_url: "https://urbantastebuds-wpengine.netdna-ssl.com/wp-content/uploads/2016/11/13076544_1686269758290212_1839862136426563207_n.jpg", description: "In every Rescue Box, you’ll get hand-selected toys, treats, and accessories for either your cat or dog. Plus, with every purchase made, you’re helping feed and vaccinate animals that are desperately in need of your help!"}
{ name: "ZooBox", bucket_id: 2, price: 19.95, image_url: "https://cdn.hellosubscription.com/wp-content/uploads/sites/2/2017/03/2e10da7b1e4f4214a39b0d6d58fe014a_600.jpeg", description: "Every month you'll receive a box filled with animal inspired gifts, stationery and creative goodies. Each month will feature a different animal and all subscribers will be entered into a monthly prize draw. We're proud supporters of the WWF, so you're not only getting a box full of animal goodies, you're also doing your bit for Mother Nature."}

-- Active Lifestyle (3)
{ name: "YogaClub", bucket_id: 3, price: 45.00, image_url: "https://s3.amazonaws.com/msa-production/boxes/images/000/002/686/medium/Untitled_design_%2815%29.png?1519840741", description: "YogaClub is your personal stylist for the yoga inspired life. Delivering high quality, brand name yoga apparel at an affordable price, we are committed to empowering women to be active, confident and mindful in everything they take on. Choose a package and frequency of delivery (monthly, bi-monthly, or quarterly) that fits your lifestyle. Then, take our proprietary style quiz to choose your sizes, favorite ways to sweat, and personal style. Every piece of activewear is handpicked by our expert stylists, just for you!"}
{ name: "Ellie", bucket_id: 3, price: 39.95, image_url: "https://cdn.shopify.com/s/files/1/1565/8379/files/ellie_banner-cat-about-desktop_2048x2048.jpg?v=1515909708", description: "A monthly activewear subscription box powered by women, for women. Choose one of three outfits below to get started. Their number one goal is help you take your workout to the next level. Each item in the Ellie box is hand-selected, tried and tested by our team."}
{ name: "Fabletics", bucket_id: 3, price: 24.00, image_url: "https://urbantastebuds-wpengine.netdna-ssl.com/wp-content/uploads/2016/10/fabletics.png", description: "When you join Fabletics, you’ll get high-quality women’s sportswear and accessories for one low price. All you have to do is take a quiz regarding your workout habits, body shape, and favorite colors, then from there you’ll be able to shop your looks. And then finally, you’ll get a box every month that contains a new, awesome workout/fitness outfit."}
{ name: "Gainzbox", bucket_id: 3, price: 32.00, image_url: "https://urbantastebuds-wpengine.netdna-ssl.com/wp-content/uploads/2016/10/March-Box.jpg", description: "With Gainzbox, you’ll get a tailored athlete box of awesome Crossfit gear delivered monthly. To get started, just choose your apparel gender, men or women, as well as your top, bottom, and underwear size. Then choose your duration and that’s it!"}
{ name: "Yogi Surprise", bucket_id: 3, price: 44.95, image_url: "https://urbantastebuds-wpengine.netdna-ssl.com/wp-content/uploads/2016/10/f85b75d588d9ed02d874733046a1870b-1024x1024.jpg", description: "What you get: When you join Yogi Surrpise, you’ll get 6-8 full size yoga lifestyle items that are all vegetarian and GMO-Free."}
{ name: "StrengthCrate", bucket_id: 3, price: 39.95, image_url:"https://urbantastebuds-wpengine.netdna-ssl.com/wp-content/uploads/2016/10/Jan_Goat-862x575.jpg", description: "When you join StrengthCrate, you’ll get a monthly box filled with gym accessories, apparel, supplements, and recovery products. Plus, you have the option to choose from 4 different box options including a warm-up crate, game-day crate, strength crate, and a G.O.A.T. crate."}
{ name: "Spin Geeks", bucket_id: 3, price: 39.99, image_url: "https://urbantastebuds-wpengine.netdna-ssl.com/wp-content/uploads/2016/10/2c4485208744431bb3b9008133c78e2d_600.png", description: "Every month, you’ll receive 4-6 full sized gym essentials that will help you explored the life of spinning (indoor cycling) such as healthy snacks, natural bath and body products, and even some geeky fitness gear."}
{ name: "FabFitFun", bucket_id: 3, price: 49.99, image_url: "http://www.latimes.com/resizer/E22eRGGYBNDL1sWeKsMKcraFKGk=/1400x0/arc-anglerfish-arc2-prod-tronc.s3.amazonaws.com/public/NHM3YUVTQFD37M5G7VQBS35C7M.jpg", description: "For busy women interested in a healthy lifestyle, but not necessarily more time at the gym, there's FabFitFun's quarterly box. This box delivers a selection of full-size healthy items to treat yourself. Subscribers might get an infuser water bottle, a DIY herb garden kit with growing tips, or a portable speaker for your workout tunes in each box, as well as beauty and fashion items and workout accessories such as this spring's double-duty yoga strap and mat carrier."}
{ name: "Courtside Crate", bucket_id: 3, price: 29.99, image_url: "https://cdn.hellosubscription.com/wp-content/uploads/sites/2/2017/03/477x376_v1.png", description: "For the ultimate fan: the official subscription crate of the NBA delivered to your door. Each box comes with 5-7 team-specific items every other month that you can’t get anywhere else. Gear, collectibles and a whole lot more."}
{ name: "Football Haul", bucket_id: 3, price: 29.99 , image_url: "https://cdn.hellosubscription.com/wp-content/uploads/sites/2/2016/01/ab6663f5a5da4336980e37d2dc0e1438.jpeg", description: "Every box is a surprise. These may include NFL action-figures, NFL bobble heads, NFL trading cards, games, puzzles, magnets and apparel. This will often include limited edition exclusive collectibles and apparel. Items will be from superstars and teams across the league!"}

-- Health & Beauty (4)
{ name: "BirchBox", bucket_id: 4, price: 10.00, image_url: "https://urbantastebuds-wpengine.netdna-ssl.com/wp-content/uploads/2016/08/1916675_10153568674801647_6504690909404393361_n.jpg", description: "When you join Birchbox, you’ll receive 5 beauty samples, all of which have been picked to match your beauty profile. Plus, whenever you review the products that you receive in your box, you’ll receive points that can go towards redeeming for full-sized products in the Birchbox shop."}
{ name: "Play! by Sephora", bucket_id: 4, price: 10.00, image_url: "https://urbantastebuds-wpengine.netdna-ssl.com/wp-content/uploads/2016/08/img_0635-2-1024x768.jpg", description: "With Play! by Sephora, you’ll receive a box of 5 deluxe skin care, hair care, and makeup samples, as well as a fragrance bonus, all of which have been handpicked form Sephora’s shelves. To get started, all you need to do is fill out a beauty profile and you’ll then get a personally curated box every month."}
{ name: "LOLA", bucket_id: 4, price: 10.00, image_url: "https://urbantastebuds-wpengine.netdna-ssl.com/wp-content/uploads/2017/01/lola-tampon-subscriptionbox.jpg", description: "LOLA is unique in the fact that it’ll deliver 100% organic tampons and feminine products to your door every month. All you need to do is just choose your product type and frequency. It’s that easy."}
{ name: "Harry's", bucket_id: 4, price: 8.00, image_url: "https://urbantastebuds-wpengine.netdna-ssl.com/wp-content/uploads/2016/11/harrys-xl.jpg", description: "When it comes to quality and affordability, Harry’s is one of the best shave clubs out there. Plus you can try it for free risk-free!"}
{ name: "Dollar Beard Club", bucket_id: 4, price: 1.00, image_url: "https://urbantastebuds-wpengine.netdna-ssl.com/wp-content/uploads/2016/11/dbc-beard-2.png", description: "With the Dollar Beard Club, you’ll get all natural beard products such as oils, balm, wax, growth accelerators, and more. All you have to do to get started is build a kit which includes choosing an oil, an essential, a shower item, an accelerator, and a accessory, and you’ll be sent that monthly. However, you can always just pick a single product and only have that in your kit which is by far the cheapest option."}
{ name: "Bulu Box", bucket_id: 4, price: 10.00, image_url: "https://urbantastebuds-wpengine.netdna-ssl.com/wp-content/uploads/2016/10/62d3b1bde1924a0c98189f47e0059041.jpeg", description: "When you join Bulu Box, you’ll discover some of  the best nutritional and weight loss products on the market today. Inside every box, you’ll receive 4-5 premium samples of products that range form sports nutrition gym gift cards, sleep aids, workout DVDs and so much more."}
{ name: "Bath Bevy", bucket_id: 4, price: 36.95, image_url: "https://img.buzzfeed.com/buzzfeed-static/static/2017-12/19/13/asset/buzzfeed-prod-fastlane-01/sub-buzz-5948-1513708837-13.jpg?crop=600:341;0,0&downsize=715:*&output-format=auto&output-quality=auto", description: "Look forward to an exciting mix of six to 10 bath products each month, such as bath bombs, bath salts, body scrubs, bubble bars, handmade soap, and so much more!"}
{ name: "TheraBox", bucket_id: 4, price: 34.99, image_url: "https://img.buzzfeed.com/buzzfeed-static/static/2017-12/19/13/asset/buzzfeed-prod-fastlane-02/sub-buzz-25996-1513708767-18.png?downsize=1500:*&output-format=auto&output-quality=auto", description: "Five to seven wellness products each month including a happiness boosting activity, organic and artisan goodies, curated by real therapists. The perfect way to put your mind at ease and truly treat yourself."}
{ name: "The Zoe Report Box of Style", bucket_id: 4, price: 99.00, image_url: "https://thumbor.forbes.com/thumbor/960x0/smart/https%3A%2F%2Fblogs-images.forbes.com%2Fsboyd%2Ffiles%2F2017%2F11%2Fboxofstyle.jpg", description: "Curated by the one and only Rachel Zoe, the Box Of Style is perfect for the fashion lover in your life. Filled with swoon-worthy fashion, beauty and lifestyle products, the Box of Style ships quarterly and features truly luxe items—items from the winter box include a faux fur stole, liquid liner, and earrings."}
{ name: "ScentBird", bucket_id: 4, price: 14.95, image_url: "https://hips.hearstapps.com/esq.h-cdn.co/assets/17/28/1499789515-gallery-1471391746-scentbird.jpg?fill=480:576&resize=980:*", description: "For guys who want to switch up their fragrances on a regular basis, Scentbird is a good alternative to spending hundreds of dollars on full bottles. Every month you can choose from an assortment of over 150 designer and niche fragrances, and then have it delivered to your home. And when each new month comes around, you can either stick with the same scent you have or switch to something new."}

-- Food & Drink (5)
{name: "Graze", bucket_id: 5, price: 13.99, image_url: "https://urbantastebuds-wpengine.netdna-ssl.com/wp-content/uploads/2016/03/13606444_675478549274270_5217970321356148255_n.jpg", description: "Graze is a mini-snack subscription box that sends a customized selection of treats weekly, bi-weekly, or monthly. They offer over 100 different snacks that you can rate online, which, over time, helps tailor your subscription to your particular snacking preferences."}
{name: "Degustabox", bucket_id: 5, price: 19.99, image_url: "https://s3.amazonaws.com/msa-production/boxes/images/000/002/240/medium/usa-banner-mysubscriptionaddiction-300x200-DIC-b.jpg?1482958054", description: "Degustabox is a subscription box that sends out a variety of food items, some which are new to the market. You won’t always be able to find these items in stores yet. These boxes typically include both snacks and other grocery items."}
{name: "Love With Food", bucket_id: 5, price: 9.99 , image_url: "https://s3.amazonaws.com/msa-production/boxes/images/000/000/206/medium/Screen_shot_2013-09-19_at_7.04.11_PM.png?1379724143", description: "Love with Food is a monthly snack and food sampling subscription box. They send only natural and organic snacks and donate a meal to charity for each box sold." }
{name: "Batch", bucket_id: 5, price: 49.00, image_url: "http://cdn-img.instyle.com/sites/default/files/styles/684xflex/public/1449527193/120715-foodie-box-4.jpg?itok=QZhqEaWF", description: "Here's something truly y'allsome: Batch curates local, handmade goodies from Nashville, Memphis, Austin, and Charleston, and then ships them right to your door. Perfect For: Country Boys, Belles, and Anyone Else Who Could Use a Little Southern Hospitality."}
{name: "Carnivore Club", bucket_id: 5, price: 50.00, image_url: "http://cdn-img.instyle.com/sites/default/files/styles/684xflex/public/1449527193/120715-foodie-box-1.jpg?itok=dUxgi0uQ", description: "Eliminate re-gifting forever with the Carnivore Club, a subscription box that promises to deliver the very best artisanal cured meat in the entire world. Perfect For: Charcuterie Addicts."}
{name: "The Cravory Cookie Box", bucket_id: 5, price: 9.95, image_url: "http://cdn-img.instyle.com/sites/default/files/styles/684xflex/public/images/2017/10/102617-crave-box-embed.jpg?itok=JufB1Evc", description: "This might be the crowd-pleasing-iest subscription box on the list. Even the Grumpy Cats in your life will melt into a puddle of love upon first bite of The Cravory's chocolate-chipped, lemon-gazed, rainbow-sprinkled, fudge-drizzled sugar fest. Perfect For: Cookie Monsters!"}
{name: "Farm To People", bucket_id: 5, price: 30.00, image_url: "http://cdn-img.instyle.com/sites/default/files/styles/684xflex/public/1449527193/120715-foodie-box-6.jpg?itok=f87EudH2", description: "This is heaven in a box for anyone who gets moon-eyed while walking through a farmer's market. Farm to People subscribers receive small-batch, artisanal goodies made with sustainable ingredients straight from farms across America."}
{name: "MistoBox", bucket_id: 5, price: 30.00, image_url: "http://cdn-img.instyle.com/sites/default/files/styles/684xflex/public/1507844132/101217-subscription-boxes-embed-3.jpg?itok=GQeSOlbI", description: "MistoBox employs coffee curators to customize your monthly box based on your java preferences and their line of 300+ artisan roasts. Their high quality beans are roasted to order so you're always assured a fresh, brew-tiful cup every morning."}
{name: "TurnTable Kitchen", bucket_id: 5, price: 25.00, image_url: "http://cdn-img.instyle.com/sites/default/files/styles/684xflex/public/1449527193/120715-foodie-box-9.jpg?itok=S500kf2p", description: "Turntable Kitchen wants to help with your next dinner party! Its Pairings Box delivers a curated food and music experience to your door by sending you a perfectly coordinated soundtrack and menu."}
{name: "Uncorked Box", bucket_id: 5, price: 30.00, image_url: "https://d3lri94xwt3wfr.cloudfront.net/0990422fc8a444be9d881b4a4147b22f_600_85_70.jpeg", description: "Each month you will receive a fun themed box filled with 5-7 wine related items. Makes a great gift for wine lovers, champagne lovers, or anyone else who loves to get presents every month!"}
{name: "Saloon Box", bucket_id: 5, price: 37.00, image_url: "https://thumbor.forbes.com/thumbor/960x0/smart/https%3A%2F%2Fblogs-images.forbes.com%2Fsboyd%2Ffiles%2F2017%2F11%2Fsaloon-box.jpg", description: "Expand your cocktail repertoire with Saloon Box! Each month, this boozy subscription box will deliver precisely-measured ingredients, top shelf liquors in sample sizes, and recipe cards for inventive cocktails, each one created by a different mixologist. In no time, you'll become an at-home bartending pro, and you'll have so much fun learning new tricks and recipes."}


